/* Main.c file generated by New Project wizard
 *
 * Created:   Mon May 25 2026
 * Processor: PIC16F877A
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include <htc.h>
//#define _XTAL_FREQ 4000000

volatile char counts = 0;

void interrupt ISR()
{
    if(INTF == 1)
    {
        __delay_ms(20);
  
        counts++;

        if(counts > 9)
            counts = 0;

    INTF = 0;   // clear interrupt flag
    }
}



void main(void)
{
    PORTB = PORTC = 0;

    TRISB = 0b00000001;   // RB0 input, RB1 output
    TRISC = 0b00000000;

    OPTION = 0b01000000;  // interrupt on rising edge

    INTCON = 0b10010000;

    while(1)
    {
       PORTC = counts;
        if(counts == 0)
        {
           RB1 = 0;
        }

        else if(counts == 1)
        {
            RB1 = 1;
            __delay_ms(900);

            RB1 = 0;
            __delay_ms(100);
        }

        else if(counts == 2)
        {
            RB1 = 1;
            __delay_ms(910);

            RB1 = 0;
            __delay_ms(90);
        }
	else if(counts == 3)
        {
            RB1 = 1;
            __delay_ms(920);

            RB1 = 0;
            __delay_ms(80);
        }
	else if(counts == 4)
        {
            RB1 = 1;
            __delay_ms(930);

            RB1 = 0;
            __delay_ms(70);
        }
	else if(counts == 5)
        {
            RB1 = 1;
            __delay_ms(940);

            RB1 = 0;
            __delay_ms(60);
        }
	else if(counts == 6)
        {
            RB1 = 1;
            __delay_ms(950);

            RB1 = 0;
            __delay_ms(50);
        }
	else if(counts == 7)
        {
            RB1 = 1;
            __delay_ms(960);

            RB1 = 0;
            __delay_ms(40);
        }
	else if(counts == 8)
        {
            RB1 = 1;
            __delay_ms(970);

            RB1 = 0;
            __delay_ms(30);
        }
	else if(counts == 9)
        {
            RB1 = 1;
            __delay_ms(990);

            RB1 = 0;
            __delay_ms(10);
        }
    }
}